### ISSUE TITLE
Carry On has failed to load correctly

### ISSUE THREAD

**Issue by schwiftyinhereforreals** [Tschipp/CarryOn#757]
I'm using NeoForge 1.21.4. Not sure what it means but it says:
java.lang.NoClassDefFoundError: net/neoforged/neoforge/event/AddReloadListenerEvent

**Comment by corellano13** [comment]
I have the same problem , if you find a solution can you tell me please

**Comment by junglehornet** [comment]
I have the same problem, using neoforge-beta 21.4.207, although I was able to get it to work on neoforge-beta 21.4.0.

**Comment by schwiftyinhereforreals** [comment]
> I have the same problem, using neoforge-beta 21.4.207, although I was able to get it to work on neoforge-beta 21.4.0.

I'm using neoforge-beta 21.4.92, so maybe that's why I'm having the problem. I may try changing to 21.4.0, but do you think it will cause any complications with my other mods if I changed my neoforge version?

**Comment by schwiftyinhereforreals** [comment]
> I have the same problem , if you find a solution can you tell me please

JungleHornet replied saying that they changed from neoforge-beta 21.4.207 to neoforge-beta 21.4.0 and that made it work, though I haven't yet tried it myself.

**Comment by junglehornet** [comment]
> > I have the same problem, using neoforge-beta 21.4.207, although I was able to get it to work on neoforge-beta 21.4.0.
> 
> I'm using neoforge-beta 21.4.92, so maybe that's why I'm having the problem. I may try changing to 21.4.0, but do you think it will cause any complications with my other mods if I changed my neoforge version?

You should try to downgrade any other mods you have installed to versions compatible with neoforge-beta 21.4.0, or 21.4.10 as that version also seemed to work. If I have some free time I'll try to see if I can fix the issue.

**Comment by junglehornet** [comment]
Looks like this is due to this breaking change to Neoforge: https://github.com/neoforged/NeoForge/pull/1915
Therefore, the mod should still work through version 21.4.83. I'm gonna see if I can code a fix myself.

**Comment by junglehornet** [comment]
I've found a fix, I'll create a PR later.

**Comment by junglehornet** [comment]
This issue will be fixed when PR #764 is merged and released.

**Comment by schabpiotr** [comment]
> This issue has been fixed in PR [#764](https://github.com/Tschipp/CarryOn/pull/764)

Unfortunately carryon still has the same error in 21.4.109-beta and later
[10:53:07] [modloading-worker-0/INFO] [ne.ne.ne.co.NeoForgeMod/NEOFORGE-MOD]: NeoForge mod loading, version 21.4.109-beta, for MC 1.21.4
[10:53:07] [modloading-worker-0/ERROR] [ne.ne.fm.ja.FMLModContainer/LOADING]: Failed to register automatic subscribers. ModID: carryon
java.lang.NoClassDefFoundError: net/neoforged/neoforge/event/AddReloadListenerEvent
	at java.base/java.lang.Class.getDeclaredMethods0(Native Method) ~[?:?] {re:mixin}
	at java.base/java.lang.Class.privateGetDeclaredMethods(Class.java:3578) ~[?:?] {re:mixin}
	at java.base/java.lang.Class.getDeclaredMethods(Class.java:2676) ~[?:?] {re:mixin}
	at MC-BOOTSTRAP/net.neoforged.bus/net.neoforged.bus.EventBus.register(EventBus.java:85) ~[bus-8.0.2.jar%23190!/:?] {}
	at MC-BOOTSTRAP/fml_loader@6.0.11/net.neoforged.fml.javafmlmod.AutomaticEventSubscriber.lambda$inject$4(AutomaticEventSubscriber.java:60) ~[loader-6.0.11.jar%23187!/:6.0] {}
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1596) ~[?:?] {re:mixin}
	at MC-BOOTSTRAP/fml_loader@6.0.11/net.neoforged.fml.javafmlmod.AutomaticEventSubscriber.inject(AutomaticEventSubscriber.java:44) ~[loader-6.0.11.jar%23187!/:6.0] {}
	at MC-BOOTSTRAP/fml_loader@6.0.11/net.neoforged.fml.javafmlmod.FMLModContainer.constructMod(FMLModContainer.java:126) ~[loader-6.0.11.jar%23187!/:6.0] {}
	at MC-BOOTSTRAP/fml_loader@6.0.11/net.neoforged.fml.ModLoader.lambda$constructMods$3(ModLoader.java:153) ~[loader-6.0.11.jar%23187!/:6.0] {}
	at MC-BOOTSTRAP/fml_loader@6.0.11/net.neoforged.fml.ModLoader.lambda$dispatchParallelTask$7(ModLoader.java:231) ~[loader-6.0.11.jar%23187!/:6.0] {}
	at java.base/java.util.concurrent.CompletableFuture.uniHandle(CompletableFuture.java:934) [?:?] {re:mixin}
	at java.base/java.util.concurrent.CompletableFuture$UniHandle.tryFire(CompletableFuture.java:911) [?:?] {}
	at java.base/java.util.concurrent.CompletableFuture$Completion.exec(CompletableFuture.java:483) [?:?] {}
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:387) [?:?] {}
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1312) [?:?] {}
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1843) [?:?] {re:computing_frames}
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1808) [?:?] {re:computing_frames}
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:188) [?:?] {}
Caused by: java.lang.ClassNotFoundException: net.neoforged.neoforge.event.AddReloadListenerEvent
	at cpw.mods.securejarhandler/cpw.mods.cl.ModuleClassLoader.loadClass(ModuleClassLoader.java:220) ~[securejarhandler-3.0.8.jar:?] {}
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526) ~[?:?] {}
	... 18 more

**Comment by junglehornet** [comment]
The PR hasn't been merged yet, did you try building from my fork that has the fix in it?

**Comment by schabpiotr** [comment]
> The PR hasn't been merged yet, did you try building from my fork that has the fix in it?

How?

**Comment by junglehornet** [comment]
Clone my fork then use the gradle runs to build the jar for whatever version you are using. If you don't know how, just wait for the PR to be merged

**Comment by Kyldof** [comment]
I solved the problem by modifying the version of neoforge I was interested in gradle.properties (neoforge_version=21.4.99-beta), and commenting out the lines in the CommonEvents.java file located in CarryOn-1.21\NeoForge\src\main\java\tschipp\carryon\events :
"import net.minecraftforge.event.server.ServerReloadEvent;"
and the "onDatapackRegister" function.

Then I built and retrieved the mod from
CarryOn-1.21\NeoForge\build\libs

[carryon-neoforge-1.21.4-2.3.0.zip](https://github.com/user-attachments/files/19389558/carryon-neoforge-1.21.4-2.3.0.zip)

**Comment by junglehornet** [comment]
That also works, I figured the code was important if it was there but I wasn't entirely sure how to refactor it. Ultimately, I ended up looking at other mods who have already fixed this issue and used that as an example to refactor the code.

**Comment by lil-fluff** [comment]
I have the same unresolved on NeoForge 21.4.121, Mod version: 2.3.0

Failure message: Carry On (carryon) has failed to load correctly
		java.lang.NoClassDefFoundError: net/neoforged/neoforge/event/AddReloadListenerEvent

Doe the PR you made fix this for all versions of NeoForge past 21.4.83? @JungleHornet

**Comment by junglehornet** [comment]
It should, however the mod author is yet to merge my PR and release the new JARs. For now, you can build your own mod JAR off of my fork, or I believe one has been posted in this thread. I think my comment's wording was a bit misleading, so I made it more obvious that it hasn't been merged yet.

**Comment by lil-fluff** [comment]
> I solved the problem by modifying the version of neoforge I was interested in gradle.properties (neoforge_version=21.4.99-beta), and commenting out the lines in the CommonEvents.java file located in CarryOn-1.21\NeoForge\src\main\java\tschipp\carryon\events : "import net.minecraftforge.event.server.ServerReloadEvent;" and the "onDatapackRegister" function.
> 
> Then I built and retrieved the mod from CarryOn-1.21\NeoForge\build\libs
> 
> [carryon-neoforge-1.21.4-2.3.0.zip](https://github.com/user-attachments/files/19389558/carryon-neoforge-1.21.4-2.3.0.zip)

I can confirm that this build/PR does work in NeoForge 21.4.121! Thanks for your effort!

**Comment by Scorpions95** [comment]
Is this issue fixed?

**Comment by junglehornet** [comment]
A fix has been made, but the mod author has not merged it yet.

**Comment by Scorpions95** [comment]
> > I solved the problem by modifying the version of neoforge I was interested in gradle.properties (neoforge_version=21.4.99-beta), and commenting out the lines in the CommonEvents.java file located in CarryOn-1.21\NeoForge\src\main\java\tschipp\carryon\events : "import net.minecraftforge.event.server.ServerReloadEvent;" and the "onDatapackRegister" function.
> > Then I built and retrieved the mod from CarryOn-1.21\NeoForge\build\libs
> > [carryon-neoforge-1.21.4-2.3.0.zip](https://github.com/user-attachments/files/19389558/carryon-neoforge-1.21.4-2.3.0.zip)
> 
> I can confirm that this build/PR does work in NeoForge 21.4.121! Thanks for your effort!

this doesnt work with one key i tried now but doesnt work
im with NeoForge

**Comment by stark-global** [comment]
> > > I solved the problem by modifying the version of neoforge I was interested in gradle.properties (neoforge_version=21.4.99-beta), and commenting out the lines in the CommonEvents.java file located in CarryOn-1.21\NeoForge\src\main\java\tschipp\carryon\events : "import net.minecraftforge.event.server.ServerReloadEvent;" and the "onDatapackRegister" function.
> > > Then I built and retrieved the mod from CarryOn-1.21\NeoForge\build\libs
> > > [carryon-neoforge-1.21.4-2.3.0.zip](https://github.com/user-attachments/files/19389558/carryon-neoforge-1.21.4-2.3.0.zip)
> > 
> > 
> > I can confirm that this build/PR does work in NeoForge 21.4.121! Thanks for your effort!
> 
> this doesnt work with one key i tried now but doesnt work im with NeoForge

I key-bind it with ` key and you have to hold the key you pick and use right click to put up.

I did just test this on NeoForge 21.4.123 and it is working as expected. Thanks so much for this update!!

**Comment by junglehornet** [comment]
> > > I solved the problem by modifying the version of neoforge I was interested in gradle.properties (neoforge_version=21.4.99-beta), and commenting out the lines in the CommonEvents.java file located in CarryOn-1.21\NeoForge\src\main\java\tschipp\carryon\events : "import net.minecraftforge.event.server.ServerReloadEvent;" and the "onDatapackRegister" function.
> > > Then I built and retrieved the mod from CarryOn-1.21\NeoForge\build\libs
> > > [carryon-neoforge-1.21.4-2.3.0.zip](https://github.com/user-attachments/files/19389558/carryon-neoforge-1.21.4-2.3.0.zip)
> > 
> > I can confirm that this build/PR does work in NeoForge 21.4.121! Thanks for your effort!
> 
> this doesnt work with one key i tried now but doesnt work
> im with NeoForge

I'm afraid any issues with the mod features are out of the scope of this issue, this is just about a loading issue.

**Comment by Scorpions95** [comment]
> > > > I solved the problem by modifying the version of neoforge I was interested in gradle.properties (neoforge_version=21.4.99-beta), and commenting out the lines in the CommonEvents.java file located in CarryOn-1.21\NeoForge\src\main\java\tschipp\carryon\events : "import net.minecraftforge.event.server.ServerReloadEvent;" and the "onDatapackRegister" function.
> > > > Then I built and retrieved the mod from CarryOn-1.21\NeoForge\build\libs
> > > > [carryon-neoforge-1.21.4-2.3.0.zip](https://github.com/user-attachments/files/19389558/carryon-neoforge-1.21.4-2.3.0.zip)
> > > 
> > > 
> > > I can confirm that this build/PR does work in NeoForge 21.4.121! Thanks for your effort!
> > 
> > 
> > this doesnt work with one key i tried now but doesnt work im with NeoForge
> 
> I key-bind it with ` key and you have to hold the key you pick and use right click to put up.
> 
> I did just test this on NeoForge 21.4.123 and it is working as expected. Thanks so much for this update!!

Nope, i test it too and i can confirm that i pick CTR and it doesnt work
even i hold the button also tried with right click, doesnt work

**Comment by junglehornet** [comment]
> > > > > I solved the problem by modifying the version of neoforge I was interested in gradle.properties (neoforge_version=21.4.99-beta), and commenting out the lines in the CommonEvents.java file located in CarryOn-1.21\NeoForge\src\main\java\tschipp\carryon\events : "import net.minecraftforge.event.server.ServerReloadEvent;" and the "onDatapackRegister" function.
> > > > > Then I built and retrieved the mod from CarryOn-1.21\NeoForge\build\libs
> > > > > [carryon-neoforge-1.21.4-2.3.0.zip](https://github.com/user-attachments/files/19389558/carryon-neoforge-1.21.4-2.3.0.zip)
> > > > 
> > > > 
> > > > I can confirm that this build/PR does work in NeoForge 21.4.121! Thanks for your effort!
> > > 
> > > 
> > > this doesnt work with one key i tried now but doesnt work im with NeoForge
> > 
> > 
> > I key-bind it with ` key and you have to hold the key you pick and use right click to put up.
> > I did just test this on NeoForge 21.4.123 and it is working as expected. Thanks so much for this update!!
> 
> Nope, i test it too and i can confirm that i pick CTR and it doesnt work even i hold the button also tried with right click, doesnt work

Try building from [my fork](github.com/JungleHornet/CarryOn), the jar posted by @Kyldof had some code commented out, but in my fork I *tried* to update the code based on what I saw in other mods who fixed this issue. I won't give any promises though, as I'm still not entirely sure what the code did, or if I updated it correctly.

**Comment by Scorpions95** [comment]
Oops i did mystake xd 
i treid CTR+right click on the normal block not on the chest or animals haha
now i tried on some usefull things
@JungleHornet 

![Image](https://github.com/user-attachments/assets/c51339cf-11d8-4af3-b85f-7cc99d9e20e4)

![Image](https://github.com/user-attachments/assets/0a1d9814-7547-49d5-acc0-6f6f0112f1b4)

![Image](https://github.com/user-attachments/assets/94bde630-0383-4269-bbbe-9323b04ecabc)
only some stuf can carry
no every item
